services:
  pickem:
    build: .
    container_name: pickem
    restart: unless-stopped
    environment:
      - PORT=3000
      - JWT_SECRET=${PICKEM_JWT_SECRET}
      - DISABLE_CRON=false
    volumes:
      - pickem_data:/app/data
    networks:
       - proxy

  pickem-family:
    build: .
    container_name: pickem-oremfam
    restart: unless-stopped
    environment:
      - PICKEM_JWT_SECRET=${PICKEM_OREMFAM_JWT_SECRET}
    volumes:
      - pickem_oremfam_data:/app/data
    networks:
      - proxy

volumes:
  pickem_data:
    external: true
    name: pickem_pickem_data
  pickem_oremfam_data:

networks:
  proxy:
    external: true
